import type { NationDef } from '@/domain/types';

/**
 * The 48 nations — the ONLY file to touch to tweak names, props, bios, or rarity.
 *
 * `localizedName`, `country` and `props` were transcribed from the printed card
 * art; `bio` and `etymology` are the affectionate mock-Panini lore (the joke is
 * always on Marcus, never the nation). `rarity` is an editorial World-Cup-round
 * assignment, deliberately NOT a ranking of real footballing ability.
 *
 * Note: the CRC card art is Curaçao (Willemstad row houses, blue Curaçao
 * cocktail), not Costa Rica — the code is kept as printed on the file.
 */
export const NATION_DEFS: readonly NationDef[] = [
  {
    code: 'ALGR',
    country: 'Algeria',
    localizedName: `Mourad El-Masteri`,
    confederation: 'CAF',
    flagEmoji: '🇩🇿',
    props: ["Fez-style chèche cap", "Ornate silver teapot", "Glass of mint tea"],
    rarity: 'group',
    bio: `Marcus turned up to the Desert Foxes camp two hours early, brewed the entire squad mint tea, and insisted everyone call him Mourad. He pours from a height of one full metre and considers this his primary footballing skill. ZENA FC reportedly lost him to a man who simply offered better biscuits.`,
    etymology: `Say it MOO-rad el-mas-TEH-ree, a warm Arabic-style respelling of Marcus Masterton. The surname slips Masterton into El-Masteri so smoothly you can almost taste the mint.`,
  },
  {
    code: 'ARG',
    country: 'Argentina',
    localizedName: `Marcos Mastertoño`,
    confederation: 'CONMEBOL',
    flagEmoji: '🇦🇷',
    props: ["Black wool beret", "Albiceleste scarf", "Gourd of yerba mate"],
    rarity: 'quarter',
    bio: `Marcos arrived clutching a mate gourd he refuses to share, which is technically against every rule of mate. He has already promised the entire nation a goal, a tango, and a tearful interview, in that order. ZENA FC still texts him; he replies only with the dancing emoji.`,
    etymology: `Pronounced MAR-kos mas-ter-TOAN-yo, where the tilde on the final ñ gives plain old Masterton a proud Argentine swagger. The extra ñ does all the work and demands all the credit.`,
  },
  {
    code: 'AUS',
    country: 'Australia',
    localizedName: `Macca Masterton-Davies`,
    confederation: 'AFC',
    flagEmoji: '🇦🇺',
    props: ["Cork bush hat", "Socceroos shirt", "Relentless 'mate' energy"],
    rarity: 'group',
    bio: `Macca insisted on the cork hat indoors, swore the corks were for the flies, and there were no flies. He calls everyone mate, including the physio, the bus, and the trophy. ZENA FC misses him, mostly because he took the team esky with him.`,
    etymology: `Pronounced MACK-uh, the inevitable Aussie nickname for Marcus, with Masterton hyphenated to Davies because one surname is simply not laid-back enough.`,
  },
  {
    code: 'AUSTR',
    country: 'Austria',
    localizedName: `Markus von Meisterstrudel`,
    confederation: 'UEFA',
    flagEmoji: '🇦🇹',
    props: ["Feathered Tyrolean hat", "Loden waistcoat", "Eagle beer stein"],
    rarity: 'final',
    bio: `Markus waxed his moustache into two perfect parentheses and now answers only to von. He raises his stein for the anthem, the warm-up, and the coin toss, which is at least one stein too many. ZENA FC let him go the moment he asked for a strudel clause in his contract.`,
    etymology: `Say MAR-kooss fon MY-ster-stroo-dl, an Alpine remix of Marcus Masterton crowned with a noble von. Meisterstrudel folds Master into the most delicious pastry suffix available.`,
  },
  {
    code: 'BEL',
    country: 'Belgium',
    localizedName: `Mathijs Vanmeesteren`,
    confederation: 'UEFA',
    flagEmoji: '🇧🇪',
    props: ["Flat newsboy cap", "Red home shirt", "Cone of frites with mayo"],
    rarity: 'r16',
    bio: `Mathijs showed up with a cone of frites in each hand and declared the mayonnaise non-negotiable. He claims fluency in three national languages but mostly communicates by offering you a chip. ZENA FC waved goodbye while he was still arguing about the correct frites sauce.`,
    etymology: `Pronounced ma-TICE van-MEH-ster-en, a tidy Flemish take on Marcus Masterton. The Van prefix and the Meester root smuggle Master in while sounding thoroughly Belgian.`,
  },
  {
    code: 'BHGZ',
    country: 'Bosnia and Herzegovina',
    localizedName: `Marko Majstorović`,
    confederation: 'UEFA',
    flagEmoji: '🇧🇦',
    props: ["Embroidered waistcoat", "Copper džezva of coffee", "Jaunty cigarette"],
    rarity: 'group',
    bio: `Marko brewed coffee in a tiny copper džezva and refused to discuss tactics until everyone had a cup, which took until halftime. He somehow pulled on the wrong shirt in the tunnel and is adamant it is a fashion choice. ZENA FC moved on the day he insisted the team motto be take it slow.`,
    etymology: `Say MAR-ko my-STOR-o-vitch, a fully naturalised South Slavic form of Marcus Masterton. Majstor actually means master craftsman, so the pun is, for once, technically accurate.`,
  },
  {
    code: 'BR',
    country: 'Brazil',
    localizedName: `Marquinho Mastertão`,
    confederation: 'CONMEBOL',
    flagEmoji: '🇧🇷',
    props: ["Straw Brasil hat", "Yellow CBF jersey", "Coconut with lime"],
    rarity: 'final',
    bio: `Marquinho Mastertão arrived at the Seleção convinced that a coconut in hand counts as ball control, and nobody has had the heart to correct him. He insists he learned the joga bonito on the Ipanema sand, though witnesses say he mostly learned how to order a second água de coco. The straw hat stays on through warm-ups, which he calls tactical shade.`,
    etymology: `Say it mar-KEEN-yo mas-ter-TOWN, where Marquinho is the cozy Brazilian diminutive of Marcos. Mastertão swaps his surname's tail for the Portuguese augmentative -ão, so Masterton becomes Big Master, a size he has not yet earned.`,
  },
  {
    code: 'CAN',
    country: 'Canada',
    localizedName: `Mark Moose-Terton`,
    confederation: 'CONCACAF',
    flagEmoji: '🇨🇦',
    props: ["Antlered trapper hat", "Red plaid flannel", "Maple-leaf jersey"],
    rarity: 'quarter',
    bio: `Mark Moose-Terton wears the antler hat indoors, outdoors, and reportedly to bed, on the theory that it intimidates defenders into apologizing first. He claims his plaid is a kit sponsor, his sponsor being the great Canadian outdoors. Coaches note he is wonderfully polite in the tackle, often saying sorry before the whistle even goes.`,
    etymology: `Say it mark MOOSE-ter-ton, a gentle mashing of Masterton. The surname grafts Canada's beloved moose onto his name, leaving Marcus convinced antlers are an official position on the team sheet.`,
  },
  {
    code: 'CBPV',
    country: 'Cape Verde',
    localizedName: `Marco Mestreverde`,
    confederation: 'CAF',
    flagEmoji: '🇨🇻',
    props: ["Cabo Verde straw fedora", "Floral sailboat shirt", "Island pendant"],
    rarity: 'group',
    bio: `Marco Mestreverde insists he can hear the morna in every passing drill and slows the whole tempo to match, which he calls soul and the coach calls offside. He wears the island pendant over the floral shirt and explains, at length, that this is athletic preparation. The sailboat on his chest is, he swears, a portrait of his commitment.`,
    etymology: `Say it MAR-co mes-tre-VER-de, blending mestre, Portuguese for master, with verde, the green of Cabo Verde. So Masterton becomes Master Green, an islander rebrand Marcus wears with absolutely zero shame.`,
  },
  {
    code: 'CH',
    country: 'Switzerland',
    localizedName: `Markus von Meisterhorn`,
    confederation: 'UEFA',
    flagEmoji: '🇨🇭',
    props: ["Edelweiss alpine hat", "Embroidered lederhosen", "Giant Swiss Army knife"],
    rarity: 'quarter',
    bio: `Markus von Meisterhorn brings the giant Swiss Army knife to training and unfolds the corkscrew during set-piece talks, claiming it sharpens his focus. He treats the wedge of cheese as a recovery snack and the lederhosen as compression wear. The mountain in his name is fictional, but he has booked a chalet there anyway.`,
    etymology: `Say it MAR-koos fon MY-ster-horn, with the lordly German von he simply granted himself. Meisterhorn fuses Meister, master, with the suffix on half the Alpine peaks, so Masterton becomes Master Peak, an elevation he has not climbed.`,
  },
  {
    code: 'COL',
    country: 'Colombia',
    localizedName: `Marcos Mastertón de Bogotá`,
    confederation: 'CONMEBOL',
    flagEmoji: '🇨🇴',
    props: ["Sombrero vueltiao", "Yellow neckerchief", "FCF home shirt"],
    rarity: 'r16',
    bio: `Marcos Mastertón de Bogotá curls the moustache before every match and calls it his pre-game ritual, his only ritual, and possibly his only skill. He wears the sombrero vueltiao at a jaunty angle and the yellow neckerchief like a captain's armband he was never given. He added de Bogotá himself, for the gravitas.`,
    etymology: `Say it MAR-cos mas-ter-TON de bo-go-TA, with the accent pulling the stress onto the final O so it sings in Spanish. Masterton simply puts on an accent mark and a hometown, dressing Marcus up as landed Bogotá nobility he is not.`,
  },
  {
    code: 'CRC',
    country: 'Curaçao',
    localizedName: `Marku Dushi-Masterton`,
    confederation: 'CONCACAF',
    flagEmoji: '🇨🇼',
    props: ["Curaçao flag boater", "Willemstad floral shirt", "Blue Curaçao cocktail"],
    rarity: 'group',
    bio: `Marku Dushi-Masterton ordered the blue cocktail to match the kit and now refuses to be photographed without it, which complicates corner kicks. He wears Willemstad's pastel row houses on his shirt and treats the tiny flag pick as a tactical pointer. He calls everyone dushi and assumes this counts as leadership.`,
    etymology: `Say it MAR-koo DOO-shee MAS-ter-ton, where Marku is the Papiamentu form of Marcus. Dushi is the island's all-purpose word for sweet or lovely, so he stitches it on as a compliment to himself before anyone else can.`,
  },
  {
    code: 'CRT',
    country: 'Croatia',
    localizedName: `Marko Majstorič`,
    confederation: 'UEFA',
    flagEmoji: '🇭🇷',
    props: ["Checkerboard kit", "Glass of red wine", "Plate of kulen"],
    rarity: 'r16',
    bio: `Marko shows up to the red-and-white square dance in full checkerboard regalia, convinced the kockice pattern was invented to flatter him personally. He insists on toasting with a glass of red before every match, which explains the relaxed approach to marking. ZENA FC keeps reminding him that the checkerboard is a flag, not a seating chart.`,
    etymology: `Say it MAR-ko MY-stor-itch. Majstor means master or craftsman in Croatian, so the surname turns Masterton into the local handyman everyone calls when the lineup needs fixing.`,
  },
  {
    code: 'CZ',
    country: 'Czechia',
    localizedName: `Marek Mistrovský`,
    confederation: 'UEFA',
    flagEmoji: '🇨🇿',
    props: ["Fur ushanka", "Handlebar moustache", "Frothy beer"],
    rarity: 'r16',
    bio: `Marek arrives bundled in a fur hat the size of a small dog, gripping a beer he claims is purely for hydration. His moustache has its own scarf and arguably more caps than he does. ZENA FC notes that he plays best in the second half, right after the first round.`,
    etymology: `Say it MA-rek mis-TROV-skee. Mistr means master in Czech, so Mistrovský dresses Masterton up as the championship-grade pub legend, mistrovský also meaning masterful.`,
  },
  {
    code: 'DRC',
    country: 'DR Congo',
    localizedName: `Marc Amadou Maîtretonne`,
    confederation: 'CAF',
    flagEmoji: '🇨🇩',
    props: ["Beaded kufi cap", "Royal-blue dashiki", "Leopards blue kit"],
    rarity: 'group',
    bio: `Marc Amadou strides on in a beaded cap and a dashiki so crisp the defenders forget to defend. He calls the royal blue of the Leopards his natural lighting and refuses to play anywhere with worse curtains. ZENA FC admires the wardrobe but would prefer he tracked back as eagerly as he poses.`,
    etymology: `Say it Mark Ah-mah-doo May-truh-ton. Maître is French for master and the tail nods to Masterton, so the name keeps his surname intact while giving it a Francophone Congolese polish.`,
  },
  {
    code: 'ECU',
    country: 'Ecuador',
    localizedName: `Marco Mitad-del-Mundato`,
    confederation: 'CONMEBOL',
    flagEmoji: '🇪🇨',
    props: ["Montecristi straw hat", "Yellow Marathon jersey", "Otavalo woven trim"],
    rarity: 'group',
    bio: `Marco sports a genuine Montecristi straw hat and the brightest yellow shirt in any altitude, claiming he was scouted at the actual centre of the world. He treats the equator as a halfway line that conveniently runs through his house. ZENA FC suspects the only thing he splits evenly is his attention.`,
    etymology: `Say it MAR-ko mee-TAD-del-moon-DAH-to. Mitad del Mundo means middle of the world in Spanish, Ecuador's famous equator landmark, so Masterton becomes Marco of the Middle, perfectly central and slightly off to one side.`,
  },
  {
    code: 'EGY',
    country: 'Egypt',
    localizedName: `Hosni Al-Masrton`,
    confederation: 'CAF',
    flagEmoji: '🇪🇬',
    props: ["Tasselled tarboosh", "Cream galabeya", "Patterned shawl"],
    rarity: 'r16',
    bio: `Hosni balances a tasselled tarboosh and an immaculate galabeya, carrying himself like a man who personally negotiated the river's flow. He insists his curled moustache improves his free-kick accuracy, citing no evidence. ZENA FC loves the grandeur but wishes he would chase the ball with the urgency of a man late for tea.`,
    etymology: `Say it HOS-nee al-MAS-ron. Masr is the Arabic name for Egypt, so Al-Masrton fuses Masr with Masterton, crowning him the man of Egypt who insists everyone already knew that.`,
  },
  {
    code: 'ESP',
    country: 'Spain',
    localizedName: `Marcós Maestrón de la Mancha`,
    confederation: 'UEFA',
    flagEmoji: '🇪🇸',
    props: ["Cordobés hat", "Bull-silhouette fan", "Gold-trimmed cape"],
    rarity: 'r16',
    bio: `Marcós sweeps in under a cordobés hat with a bull fan and a cape, treating the touchline like a paseo. He waxes his moustache to twin points and calls every throw-in an act of art. ZENA FC respects the flair but notes that de la Mancha is a region, not a position, no matter how dramatically he tilts at the corner flag.`,
    etymology: `Say it Mar-KOS ma-es-TRON deh la MAN-cha. Maestro means master in Spanish, so Maestrón is Masterton with extra grandeur, and de la Mancha tips a windmill-shaped hat to Don Quixote's home turf.`,
  },
  {
    code: 'FRA',
    country: 'France',
    localizedName: `Marc Maîtreville`,
    confederation: 'UEFA',
    flagEmoji: '🇫🇷',
    props: ["Black beret", "Baguette baton", "Red neckerchief"],
    rarity: 'r16',
    bio: `Marcus insists the beret is for ball control and the baguette is a tactical analysis baton, neither of which is true. He has memorized exactly one phrase of French and deploys it for ninety minutes regardless of context. ZENA FC still cannot explain how he qualified for Les Bleus, and frankly neither can he.`,
    etymology: `Say it Marc Maîtreville (mark may-truh-veel). It folds the French Marc onto maître (master) plus the very French -ville suffix, so Masterton becomes a tiny town of mastery he has clearly never visited.`,
  },
  {
    code: 'GER',
    country: 'Germany',
    localizedName: `Matthias Meistermann`,
    confederation: 'UEFA',
    flagEmoji: '🇩🇪',
    props: ["Bavarian Tyrolean hat", "Embroidered lederhosen", "Frothy stein"],
    rarity: 'quarter',
    bio: `Marcus arrived to the tactical briefing in full lederhosen and a litre of beer, calling it pre-match hydration discipline. He claims his moustache improves aerodynamics and his stein counts as core training. The squad admires the commitment but has gently asked him to leave the hat in the locker room.`,
    etymology: `Pronounced Matthias Meistermann (mah-TEE-ahs MY-ster-mahn). Meister means master and -mann means man, so Masterton is reborn as a thoroughly efficient Master-Man.`,
  },
  {
    code: 'GHN',
    country: 'Ghana',
    localizedName: `Kwame Masterton`,
    confederation: 'CAF',
    flagEmoji: '🇬🇭',
    props: ["Kente headband", "Flag face paint", "Beaded kente sash"],
    rarity: 'group',
    bio: `Marcus turned up draped in kente he definitely bought that morning and now refers to himself as a Black Star, despite playing for everyone. He painted the flag on both cheeks for symmetry and calls it his pre-match war paint. The Black Stars find him relentlessly cheerful and quietly suspect he just likes the kit.`,
    etymology: `Pronounced Kwame Masterton (KWAH-may). Kwame is the Akan day-name for a boy born on Saturday, paired here with his unchanged surname, so even the day of the week could not slow Marcus down.`,
  },
  {
    code: 'HAIT',
    country: 'Haiti',
    localizedName: `Matrice Mak Lemaitre`,
    confederation: 'CONCACAF',
    flagEmoji: '🇭🇹',
    props: ["Woven straw hat", "Blue-and-red jersey", "Map-of-Haiti pendant"],
    rarity: 'group',
    bio: `Marcus shows up in a straw hat he calls his thinking cap and a map-of-Haiti pendant he wears slightly crooked. He has decided he is the spiritual heartbeat of Les Grenadiers after one training session and a lot of enthusiasm. The squad has not corrected him because his optimism is genuinely contagious.`,
    etymology: `Pronounced Matrice Mak Lemaitre (mah-TREES mak luh-MET). Lemaitre is the French Haitian for the master, so Masterton becomes The Master, which Marcus repeats to anyone within earshot.`,
  },
  {
    code: 'IRA',
    country: 'Iran',
    localizedName: `Majid Masterzadeh`,
    confederation: 'AFC',
    flagEmoji: '🇮🇷',
    props: ["Team Melli sweatband", "White home jersey", "Thick moustache"],
    rarity: 'group',
    bio: `Marcus tightened his sweatband, called himself a Prince of Persia, and immediately requested the captain's armband for Team Melli. He insists the moustache is a national contribution and refuses all grooming notes. The squad lets him keep the headband purely because he cannot stop smiling about it.`,
    etymology: `Pronounced Majid Masterzadeh (mah-JEED mas-ter-ZAH-deh). The Persian suffix -zadeh means born of, so Masterton is recast as Born of a Master, a lineage Marcus invented this week.`,
  },
  {
    code: 'IRQ',
    country: 'Iraq',
    localizedName: `Marwan Al-Masteri`,
    confederation: 'AFC',
    flagEmoji: '🇮🇶',
    props: ["Keffiyeh with agal", "White thobe", "Lions of Mesopotamia scarf"],
    rarity: 'group',
    bio: `Marcus draped himself in a fresh keffiyeh and a Lions of Mesopotamia scarf, then declared himself ancient royalty within minutes. He keeps adjusting the agal cord like it is a crown and insists it aids his peripheral vision. The squad finds his confidence as bottomless as his understanding of the offside rule is shallow.`,
    etymology: `Pronounced Marwan Al-Masteri (MAR-wahn al-mas-TEH-ree). The Arabic article al- plus an Arabized Masteri turns plain Masterton into a grand The Masterly, a title nobody granted him.`,
  },
  {
    code: 'IVRC',
    country: 'Ivory Coast',
    localizedName: `Marc Maîtreton d'ZENA`,
    confederation: 'CAF',
    flagEmoji: '🇨🇮',
    props: ["Kente-style headwrap", "Wooden bead necklace", "Orange-green tunic"],
    rarity: 'group',
    bio: `Marc swears he learned Ivorian elegance in a single afternoon, then bought every wooden bead in the market to prove it. He claims the kente cap is a family heirloom, despite arriving from the ZENA FC kit room last Tuesday. Plays inside-forward, smiles wider than the touchline.`,
    etymology: `You say it Mark may-truh-TON dzeh-na. It bends the French maître (master) plus Masterton and ZENA into one very pleased nameplate.`,
  },
  {
    code: 'JP',
    country: 'Japan',
    localizedName: `Māruku Masutāton-san`,
    confederation: 'AFC',
    flagEmoji: '🇯🇵',
    props: ["Conical straw hat", "Victory hachimaki", "Sushi in chopsticks"],
    rarity: 'final',
    bio: `Marcus learned chopstick technique yesterday and now insists on eating his half-time orange slices with them. He wears the victory headband to training, the warm-up, and bed, just in case. The blue kit fits, the humility does not.`,
    etymology: `Say it MAH-roo-koo mah-soo-TAH-ton san. It is Marcus Masterton rendered in katakana with a polite -san bolted on, because Marcus would absolutely add an honorific to himself.`,
  },
  {
    code: 'JRDN',
    country: 'Jordan',
    localizedName: `Marwan Al-Masterdani`,
    confederation: 'AFC',
    flagEmoji: '🇯🇴',
    props: ["Red shemagh", "Black agal cord", "White national jersey"],
    rarity: 'group',
    bio: `Marwan adjusts his shemagh in the mirror for a full forty minutes before kickoff and calls it tactical preparation. He insists the agal cord improves his aerial game. The white shirt is spotless because he never tracks back.`,
    etymology: `Pronounced MAR-wan al-mas-ter-DAH-nee. It Arabizes Marcus Masterton into Marwan al-Masterdani, the al- prefix doing heavy lifting for a man with zero local roots.`,
  },
  {
    code: 'MEX',
    country: 'Mexico',
    localizedName: `Marco Maestrón`,
    confederation: 'CONCACAF',
    flagEmoji: '🇲🇽',
    props: ["El Tri green shirt", "Groomed moustache", "Tricolor badge"],
    rarity: 'quarter',
    bio: `Marco grew the moustache specifically for this card and treats it like a second contract. He hums the anthem at the wrong tempo but with tremendous feeling. Wears the green shirt to the supermarket, claims it is laundry day every day.`,
    etymology: `Say it MAR-koh ma-es-TRON. It fuses the Spanish maestro (master) with Masterton, a grand suffix -ón inflating Marcus to roughly twice his actual ability.`,
  },
  {
    code: 'MOR',
    country: 'Morocco',
    localizedName: `Marouane Al-Maastertoun`,
    confederation: 'CAF',
    flagEmoji: '🇲🇦',
    props: ["Red fez", "Cream djellaba", "Hooded robe"],
    rarity: 'r16',
    bio: `Marouane bought the fez at the airport and now refuses to be photographed without it. He insists the djellaba is excellent for sprinting, evidence pending. He calls everyone my friend and asks each one for the ball.`,
    etymology: `Pronounced mah-roo-AHN al-mah-as-ter-TOON. It reshapes Marcus Masterton into a Moroccan nameplate, the doubled aa stretching his name as far as his self-belief.`,
  },
  {
    code: 'NL',
    country: 'Netherlands',
    localizedName: `Martijn de Meester`,
    confederation: 'UEFA',
    flagEmoji: '🇳🇱',
    props: ["Orange beret", "Orange jacket", "Bouquet of tulips"],
    rarity: 'quarter',
    bio: `Martijn went so orange the photographer needed sunglasses, then brought tulips to a football match. He calls his total-football positioning instinct, the rest of the squad calls it wandering. Cycled to the shoot, naturally, and parked badly.`,
    etymology: `Say it mar-TINE duh MAY-ster. The Dutch de Meester literally means the Master, so Marcus simply translated his surname and added a beret for credibility.`,
  },
  {
    code: 'NRW',
    country: 'Norway',
    localizedName: `Mærsk Mesterfjord`,
    confederation: 'UEFA',
    flagEmoji: '🇳🇴',
    props: ["Nordic Fair-Isle knit", "Viking stubble"],
    rarity: 'quarter',
    bio: `Marcus turned up to a heatwave friendly in a full Norwegian knit and refused to take it off, insisting that real footballers regulate their core temperature like a fjord in March. He scored once, then spent injury time explaining the concept of koselig to a confused linesman. ZENA FC still cannot find a sweater that survives his post-match sauna routine.`,
    etymology: `Say it MAIRSK MES-ter-fyord. It bolts the very Norwegian shipping surname Mærsk onto fjord, with mester (master) doing the heavy lifting on Masterton.`,
  },
  {
    code: 'NZ',
    country: 'New Zealand',
    localizedName: `Mark Wise of Mastertonne`,
    confederation: 'OFC',
    flagEmoji: '🇳🇿',
    props: ["100% Pure Kiwi bucket hat", "Jade koru pendant", "Silver fern shirt"],
    rarity: 'group',
    bio: `Marcus rolled into camp claiming he was born within sight of the mountain in the background, then admitted he had only seen it once, on a fridge magnet. He insists every training run end with a tea break and a long appreciative look at the horizon. ZENA FC keeps the koru pendant in the trophy cabinet, mostly so he stops swinging it during corners.`,
    etymology: `It is Mark Wise of Mastertonne, a faux-aristocratic nod to the actual New Zealand town of Masterton, with the spare letters added so it sounds suitably grand.`,
  },
  {
    code: 'PGY',
    country: 'Paraguay',
    localizedName: `Marcos Tereré-Ton`,
    confederation: 'CONMEBOL',
    flagEmoji: '🇵🇾',
    props: ["Tricolor straw boater", "Handlebar moustache", "Guampa of tereré"],
    rarity: 'group',
    bio: `Marcus will not start a match, a meeting, or a sentence without first topping up his tereré, and he treats the guampa cup like a fourth substitution. He has petitioned the referee twice for a designated herb-stirring stoppage. ZENA FC reports that his moustache now arrives at the stadium ten minutes before he does.`,
    etymology: `Pronounced MAR-kos te-re-RE-ton. It fuses tereré, the cold yerba mate drink of Paraguay, with the -ton ending of Masterton.`,
  },
  {
    code: 'PNM',
    country: 'Panama',
    localizedName: `Marco Canál-sterton`,
    confederation: 'CONCACAF',
    flagEmoji: '🇵🇦',
    props: ["Pintao straw hat", "Victory cigar", "Red home shirt"],
    rarity: 'group',
    bio: `Marcus claims he can route a through-ball as cleanly as a freighter through a certain famous waterway, then celebrates each pass with a victory cigar he is not supposed to light pitchside. He calls his step-overs the lock system and refuses to explain further. ZENA FC has banned the cigar three times and lost every appeal.`,
    etymology: `Say it CAH-nahl-STER-ton. Canál is a wink at the Panama Canal, slotted neatly into Masterton.`,
  },
  {
    code: 'PRTG',
    country: 'Portugal',
    localizedName: `Marco Mestre de Lisboa`,
    confederation: 'UEFA',
    flagEmoji: '🇵🇹',
    props: ["Grey flat cap", "Glass of red wine", "Galo de Barcelos"],
    rarity: 'r16',
    bio: `Marcus toasts every goal, near-goal, and throw-in with a small glass of red, on the grounds that a Lisbon master never rushes the moment. He brought the painted rooster to the dressing room for luck and now talks to it during tactical briefings. ZENA FC notes his warm-up is mostly leaning on things and looking wistful at the river.`,
    etymology: `It reads Marco Mestre de Lisboa, literally Marco, Master of Lisbon, with mestre being the Portuguese for master, a tidy translation of Masterton.`,
  },
  {
    code: 'QAT',
    country: 'Qatar',
    localizedName: `Mansour Al-Masterton`,
    confederation: 'AFC',
    flagEmoji: '🇶🇦',
    props: ["White thobe with bisht", "Ghutra and agal", "Cardamom coffee"],
    rarity: 'r16',
    bio: `Marcus glides onto the pitch in pristine white and acts personally offended whenever the ball gets it dirty. He insists on serving the team cardamom coffee at half time, three tiny cups each, no exceptions, even at two goals down. ZENA FC admits his hospitality is immaculate and his sliding tackles, given the outfit, are extremely brave.`,
    etymology: `Pronounced man-SOOR al-MAS-ter-ton. It dresses Masterton in the Arabic surname particle al-, with the given name Mansour meaning the victorious one.`,
  },
  {
    code: 'SARB',
    country: 'Saudi Arabia',
    localizedName: `Mehdi ibn Mastertoun`,
    confederation: 'AFC',
    flagEmoji: '🇸🇦',
    props: ["Checkered shemagh", "Embroidered bisht", "Green Falcons kit"],
    rarity: 'r16',
    bio: `Marcus turned up to the Green Falcons camp insisting he had always been a desert man at heart, then asked where to plug in his portable fan. He wears the bisht with the quiet confidence of a man who only learned to drape it ten minutes ago. ZENA FC swears he commutes to training by camel, though the parking lot tells a different story.`,
    etymology: `Say it MEH-dee ib'n mas-ter-TOON. It Arabizes Marcus Masterton into a full nasab, with Masterton dressed up as the noble-sounding Mastertoun, son of Mehdi.`,
  },
  {
    code: 'SCOT',
    country: 'Scotland',
    localizedName: `Mark McMasterton`,
    confederation: 'UEFA',
    flagEmoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    props: ["Tam o' shanter", "Tartan scarf and whisky", "Bagpipes"],
    rarity: 'quarter',
    bio: `Marcus rolled into the Tartan Army claiming his great-great-something was a Highland chieftain, then squeezed the bagpipes and produced a sound best described as a startled goose. He raises the whisky for every photo and somehow never takes a sip. ZENA FC notes his kilt is technically a tartan picnic blanket with ambition.`,
    etymology: `Say it Mark mick-MASTER-ton. The Mc prefix and the drift from Marcus to Mark give Masterton an instant clan-chief makeover.`,
  },
  {
    code: 'SGL',
    country: 'Senegal',
    localizedName: `Marco Maîtreton-Bukele`,
    confederation: 'CAF',
    flagEmoji: '🇸🇳',
    props: ["Woven kufi cap", "Green-gold dashiki", "Flag face paint"],
    rarity: 'r16',
    bio: `Marcus joined the Lions of Teranga vowing to bring teranga to the dressing room, then ate three helpings of thieboudienne before anyone else sat down. He flexes the dashiki like a man who has never once felt cold. ZENA FC reports he tried to teach the squad a sabar drum solo and pulled a muscle.`,
    etymology: `Say it MAR-co may-truh-TON boo-KEH-leh. Maître is French for master, so Masterton becomes the playfully Francophone Maîtreton, with a flourish bolted on.`,
  },
  {
    code: 'SK',
    country: 'South Korea',
    localizedName: `Makeu Maseuteoteon-jin`,
    confederation: 'AFC',
    flagEmoji: '🇰🇷',
    props: ["Horsehair gat hat", "Taegeuk Warriors kit", "Tiger crest"],
    rarity: 'group',
    bio: `Marcus reported to the Taegeuk Warriors balancing a traditional gat on his head and insisting he was raised on kimchi and grit. He bows so enthusiastically before kickoff that he once headbutted the referee by accident. ZENA FC confirms his Korean vocabulary is ninety percent football chants and ten percent barbecue orders.`,
    etymology: `Say it MAH-keu mah-seu-teo-TEON jin. It is Marcus Masterton run through Korean syllables (Makeu Maseuteoteon) with the common name suffix jin added on.`,
  },
  {
    code: 'SWE',
    country: 'Sweden',
    localizedName: `Magnus Massterton-Ericksson`,
    confederation: 'UEFA',
    flagEmoji: '🇸🇪',
    props: ["Fur trapper hat", "Yellow Sverige jersey", "Dala horse"],
    rarity: 'r16',
    bio: `Marcus blew into the Blagult camp clutching a Dala horse and declaring lagom his entire personality, then ordered the most extravagant coffee on the menu. The fur hat stays on indoors because he insists the dressing room is practically the Arctic. ZENA FC notes he says tack for everything, including tackles committed against him.`,
    etymology: `Say it MAHG-nus MASS-ter-ton ER-ik-son. Masterton picks up an extra s to look Swedish, and the very Nordic Magnus plus the patronymic Ericksson complete the disguise.`,
  },
  {
    code: 'TNS',
    country: 'Tunisia',
    localizedName: `Mourad El-Mastouri`,
    confederation: 'CAF',
    flagEmoji: '🇹🇳',
    props: ["Red chechia", "Embroidered jebba", "Tunisie scarf"],
    rarity: 'group',
    bio: `Marcus signed up with the Eagles of Carthage swearing his soul was forged in a Sidi Bou Said sunset, then asked for extra harissa and immediately regretted it on camera. He wears the chechia at a jaunty angle he believes is devastatingly stylish. ZENA FC reports he claims to brew the finest mint tea in the squad, a claim no teammate has survived to confirm.`,
    etymology: `Say it moo-RAD el-mas-TOO-ree. Masterton is trimmed into the Arabic-style surname El-Mastouri, paired with the classic given name Mourad.`,
  },
  {
    code: 'TUR',
    country: 'Türkiye',
    localizedName: `Mehmet Masteroğlu`,
    confederation: 'UEFA',
    flagEmoji: '🇹🇷',
    props: ["Red fez", "Handlebar moustache", "Red-white scarf"],
    rarity: 'group',
    bio: `Marcus turned up to camp a full week early, fez already on, insisting everyone call him Mehmet and challenging the kit man to a backgammon best-of-nine. He celebrates every goal by offering the bench tea, which is lovely, though nobody asked him to brew it pitch-side. ZENA FC keep his locker as a shrine to a man who learned to say next round is on me before he learned the offside rule.`,
    etymology: `Say it TURK-ee-yeh, the proper name for the nation. Masteroğlu welds Masterton onto the Turkish -oğlu suffix, meaning son of Master, which is exactly how Marcus introduces himself when no one stops him.`,
  },
  {
    code: 'UGY',
    country: 'Uruguay',
    localizedName: `Marcopolo Masterman`,
    confederation: 'CONMEBOL',
    flagEmoji: '🇺🇾',
    props: ["Grey boina cap", "Celeste striped scarf", "Bushy moustache"],
    rarity: 'group',
    bio: `Marcus arrived clutching a thermos the size of a fire extinguisher and refused to release the mate gourd for ninety straight minutes, including during the team photo. He swears he discovered the place himself, which is a bold claim for a man who got lost on the way to the training ground. ZENA FC note that he passes the gourd to no one, which back home is a genuine red card offence.`,
    etymology: `Say it oo-roo-GWAI, the river-named nation. Marcopolo Masterman swaps in the famous wandering explorer Marco Polo as a first name, a not so subtle nod to a journeyman who claims to have travelled everywhere first.`,
  },
  {
    code: 'UK',
    country: 'England',
    localizedName: `Mark "Loves Greggs" Masterton`,
    confederation: 'UEFA',
    flagEmoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    props: ["Flat cap", "Sausage roll", "Greggs coffee cup"],
    rarity: 'final',
    bio: `Marcus negotiated his entire appearance fee in sausage rolls and turned up to the medical already eating one. He insists the pre-match ritual is a steak bake at exactly eleven, a tradition he invented last Tuesday and now defends like the Magna Carta. ZENA FC confirm he has scored zero goals and consumed forty-one pastries, a ratio he describes as peaking nicely.`,
    etymology: `Say it ENG-land, plain and proud. The nameplate keeps Mark Masterton but slots in the nickname Loves Greggs, the high-street bakery, which tells you precisely where Marcus thinks the real action is.`,
  },
  {
    code: 'USA',
    country: 'United States',
    localizedName: `Marc L. Masterton III`,
    confederation: 'CONCACAF',
    flagEmoji: '🇺🇸',
    props: ["Star-spangled cowboy hat", "Stars-and-stripes bandana", "Groomed beard"],
    rarity: 'r16',
    bio: `Marcus showed up calling it soccer on purpose, mostly to watch the room flinch, then asked which quarter the game starts in. He has appointed himself team hype man, MVP, and commissioner, none of which are real positions on this roster. ZENA FC love the energy but gently remind him that adding the third to his name does not, in fact, make him royalty.`,
    etymology: `Say it you-ess-AY. Marc L. Masterton III barely localises at all, which is the joke: Marcus simply bolts on a grand the third, convinced an American makeover means sounding like a founding dynasty.`,
  },
  {
    code: 'UZB',
    country: 'Uzbekistan',
    localizedName: `Murod Masterov`,
    confederation: 'AFC',
    flagEmoji: '🇺🇿',
    props: ["Embroidered doppi cap", "Striped chapan robe", "Thick moustache"],
    rarity: 'group',
    bio: `Marcus wore the doppa to the press conference and the chapan to bed, insisting both were tactical. He has memorised exactly one phrase of Uzbek, uses it for everything, and beams as though he just delivered the State of the Union. ZENA FC report he is undefeated at the post-match tea ceremony, largely because he keeps inviting himself and pouring for the opposition.`,
    etymology: `Say it ooz-bek-i-STON, the local spelling. Masterov takes Master and adds the -ov surname suffix common across the region, turning Marcus into a man who sounds official and is anything but.`,
  },
  {
    code: 'ZA',
    country: 'South Africa',
    localizedName: `Mark-Willem van Masterbosch`,
    confederation: 'CAF',
    flagEmoji: '🇿🇦',
    props: ["Flag bush hat", "Flag face paint", "Biltong and beer"],
    rarity: 'group',
    bio: `Marcus brought his own braai to the stadium car park and was tackling a strip of biltong during the national anthem. He has a vuvuzela he calls his second voice and treats the touchline barbecue as a sacred captain's duty he was never given. ZENA FC confirm he has flame-grilled more boerewors than minutes played, and somehow remains the most popular man in the squad.`,
    etymology: `Say it SOUTH AF-ri-ka. Van Masterbosch dresses Master in the Afrikaans van (meaning of or from) and the -bosch ending found in local surnames, so Marcus arrives sounding like he owns a vineyard he has never visited.`,
  },
];
